enum StarshipsType {
  SET_STARSHIPS_STATUS = 'SET_STARSHIPS_STATUS',
  SET_STARSHIPS = 'SET_STARSHIPS',
  SET_STARSHIPS_SORT_TYPE = 'SET_STARSHIPS_SORT_TYPE',
  SET_STARSHIPS_SORT_FIELD = 'SET_STARSHIPS_SORT_FIELD',
};


export default StarshipsType;
