enum PersonsType {
  SET_PERSONS_STATUS = 'SET_PERSONS_STATUS',
  SET_PERSONS = 'SET_PERSONS',
  SET_PERSONS_SORT_TYPE = 'SET_PERSONS_SORT_TYPE',
  SET_PERSONS_SORT_FIELD = 'SET_PERSONS_SORT_FIELD',
};


export default PersonsType;
