enum PersonsType {
  SET_PERSONS_STATUS = 'SET_PERSONS_STATUS',
  SET_PERSONS = 'SET_PERSONS',
  SET_PERSONS_SORT_TYPE = 'SET_PERSONS_SORT_TYPE',
  SET_PERSONS_SORT_FIELD = 'SET_PERSONS_SORT_FIELD',
  SET_PERSON_COMMENTS_STATUS = 'SET_PERSON_COMMENTS_STATUS',
  SET_PERSON_COMMENTS = 'SET_PERSON_COMMENTS',
};


export default PersonsType;
