enum PlanetsType {
  SET_PLANETS_STATUS = 'SET_PLANETS_STATUS',
  SET_PLANETS = 'SET_PLANETS',
  SET_PLANETS_SORT_TYPE = 'SET_PLANETS_SORT_TYPE',
  SET_PLANETS_SORT_FIELD = 'SET_PLANETS_SORT_FIELD',
};


export default PlanetsType;
